// import * as colors from './colors';
import colors from './colors';

export const palette = {
    primary: {
        light: colors.green[60],
        main: colors.green[50],
        dark: colors.green[40],
        contrastText: colors.common.white,
        lightBg: colors.green[100],
        border: colors.green[80],
        textDark: colors.green[20],
    },
    secondary: {
        light: colors.orange[60],
        main: colors.orange[50],
        dark: colors.orange[40],
        contrastText: colors.common.white,
        lightBg: colors.orange[100],
        border: colors.orange[80],
        textDark: colors.orange[20],
    },
    error: {
        light: colors.red[60],
        main: colors.red[50],
        dark: colors.red[40],
        contrastText: colors.common.white,
        lightBg: colors.red[100],
        border: colors.red[80],
        textDark: colors.red[20],
    },
    warning: {
        light: colors.yellow[70],
        main: colors.yellow[60],
        dark: colors.yellow[50],
        contrastText: colors.grey[10],
        lightBg: colors.yellow[100],
        border: colors.yellow[80],
        textDark: colors.yellow[20],
    },
    info: {
        light: colors.blue[60],
        main: colors.blue[50],
        dark: colors.blue[40],
        contrastText: colors.common.white,
        lightBg: colors.blue[100],
        border: colors.blue[80],
        textDark: colors.blue[20],
    },
    success: {
        light: colors.green[60],
        main: colors.green[50],
        dark: colors.green[40],
        contrastText: colors.common.white,
        lightBg: colors.green[100],
        border: colors.green[80],
        textDark: colors.green[20],
    },
    grey: {
        50: colors.grey[100],
        100: colors.grey[90],
        200: colors.grey[80],
        300: colors.grey[70],
        400: colors.grey[60],
        500: colors.grey[50],
        600: colors.grey[40],
        700: colors.grey[30],
        800: colors.grey[20],
        900: colors.grey[10],
        A100: colors.grey[90],
        A200: colors.grey[80],
        A400: colors.grey[60],
        A700: colors.grey[30],
    },
    text: {
        primary: colors.grey[10],
        secondary: colors.grey[50],
        disabled: colors.grey[70],
        hint: colors.grey[80],
        toolbar: colors.grey[90],
        suppressed: colors.grey[90],
        contrast: colors.grey[100],
        white: colors.common.white,
    },
    background: {
        paper: colors.common.white,
        default: colors.grey[100],
        level1: colors.grey[90],
        level2: colors.grey[80],
        backdrop: colors.grey[60],
        snackbar: colors.green[60],
        tooltip: colors.grey[40],
    },
    border: {
        stroke: colors.grey[100],
        strokeDark: colors.grey[50],
        white: colors.common.white,
        divider: colors.grey[90],
    },
    icon: {
        default: colors.grey[70],
        dark: colors.grey[50],
        active: colors.green[60],
        contrast: colors.grey[100],
        white: colors.common.white,
    },
    action: {
        odd: colors.grey[100],
        active: colors.green[100],
        hover: colors.green[90],
        selected: colors.green[100],
        disabled: colors.grey[90],
        focus: colors.green[100],
    }
}