
name: cloudrun-deploy-develop
on:
  push:
    branches:
      - develop

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: treeo-dev-cloud-run
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  DEPLOYMENT_NAME: cloud-run-deployment
  IMAGE: treeo-cloud-dev

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: 'google-github-actions/setup-gcloud@v0'
      with:
        service_account_key: ${{ secrets.GKE_CLOUD_RUN_SA_KEY }}
        export_default_credentials: true
    
    # Configure Docker with Credentials
    - name: Configure Docker
      run: |
        gcloud auth configure-docker
      
    # # Build the Docker image
    # - name: Build & Publish
    #   run: |
    #     gcloud config set project ${{ secrets.GKE_PROJECT }}
    #     gcloud builds submit --tag gcr.io/${{ secrets.GKE_PROJECT }}/${{ secrets.DEPLOYMENT_NAME_PRODUCTION }}
    #     gcloud config set run/region us-central1

    # Build the Docker image
    - name: Build
      run: |-
        docker build -f Dockerfile.prod \
          --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
      
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        gcloud run deploy treeo-dev --image gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA \
        --port 80 \
        --platform managed \
        --allow-unauthenticated \
        --memory 512M \
        --region europe-west1 \
        --project treeo-dev